/**
 * @author Prathima S R
 * @email ps185311@ncr.com
 * @create date 2020-03-03 11:37:12
 * @modify date 2020-03-03 11:37:12
 */

export default {
    //user actions
    ENTER_USER_NAME: 'ENTER_USER_NAME',
    ENTER_USER_PASSWORD: 'ENTER_USER_PASSWORD',
    ENTER__REPEAT_USER_PASSWORD: 'ENTER__REPEAT_USER_PASSWORD',
    ADD_USER_ALL_DATA: 'ADD_USER_ALL_DATA',
    USER_RESET: 'REPORT_RESET',
    ENTER_USER_ROLE: 'ENTER_USER_ROLE',

    GET_CAPSULES: 'GET_CAPSULES',
    GET_HISTORY: 'GET_HISTORY',
    GET_ROADSTER: 'GET_ROADSTER'
};
